number1 = int(input("Enter a first number:"))
number2 = int(input("Enter a second number:"))
number3 = int(input("Enter a third number:"))
number4 = int(input("Enter a fourth number:"))
number5 = int(input("Enter a fifth number:"))
number6 = int(input("Enter a sixth number:"))
numbers = (number1,number2,number3,number4,number5,number6)
print(f"Total numbers:{numbers.count(10)}")
print(f"The index:{numbers.index(20)}")