print("Student Profile")
name = input("Enter your name:")
age = int(input("Enter your age:"))
university = input("Enter your university name:")
semester =int(input("Enter your semester:"))
print(f"The student name is:{name}")
print(f"The age is:{age}")
print(f"The university is:{university}")
print(f"The semester is:{semester}")