print("Student Profile")
name = input("Enter your name:")
age = int(input("Enter your age:"))
university = input("Enter your university name:")
semester =int(input("Enter your semester:"))
print("The student name is:",name)
print("The age is:",age)
print("The university is:",university)
print("The semester is:",semester)